// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_Grupo8_TPI.Models;

public partial class Carrito
{
    public int IdCarrito { get; set; }

    public int IdCliente { get; set; }

    public int IdSuministro { get; set; }

    public int Cantidad { get; set; }

    public double PrecioUnitario { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Suministro IdSuministroNavigation { get; set; }
}