// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_Grupo8_TPI.Models;

public partial class Meses
{
    public int IdMes { get; set; }

    public string Mes { get; set; }

    public virtual ICollection<Cobertura> Coberturas { get; set; } = new List<Cobertura>();
}