// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_Grupo8_TPI.Models;

public partial class Role
{
    public int IdRol { get; set; }

    public string DescripcionRol { get; set; }

    public virtual ICollection<EmpleadosInterno> EmpleadosInternos { get; set; } = new List<EmpleadosInterno>();
}