// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_Grupo8_TPI.Models;

public partial class TipoContacto
{
    public int IdTipoContacto { get; set; }

    public string Tipo { get; set; }

    public virtual ICollection<Contacto> Contactos { get; set; } = new List<Contacto>();
}